### PR TITLE
rm version from toolchain names

### PR DESCRIPTION
**Pull request by garymm**
we only use one version of each so this is simpler

Change-Id: Iac008c1403710966bca47db958e627c7b079ea26

### CODE REVIEW

**Review by oliverlee — APPROVED** [review]

**Comment by oliverlee** [comment]
I tried out using squash merge for a project over the summer and it was nice how it creates a link to the PR in the commit message. Have you tried that?

**Comment by garymm** [comment]
Yeah that's what we use by default at work.

**Comment by oliverlee** [comment]
Do you know if it works well with 
multiple PRs and automerge?

**Comment by garymm** [comment]
I don't know, we should try it.

**Pull request merged**
